// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhotoSortingApp.Data;

#nullable disable

namespace PhotoSortingApp.Data.Migrations
{
    [DbContext(typeof(PhotoCatalogDbContext))]
    [Migration("20260227182536_AddPeopleAndAnimalsCsv")]
    partial class AddPeopleAndAnimalsCsv
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("PhotoSortingApp.Domain.Models.PhotoAsset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AnimalsCsv")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("CameraMake")
                        .HasColumnType("TEXT");

                    b.Property<string>("CameraModel")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateTaken")
                        .HasColumnType("TEXT");

                    b.Property<int>("DateTakenSource")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FileCreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FileLastWriteUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FolderPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("IndexedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("PeopleCsv")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("ScanRootId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sha256")
                        .HasColumnType("TEXT");

                    b.Property<string>("TagsCsv")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DateTaken");

                    b.HasIndex("FullPath");

                    b.HasIndex("ScanRootId");

                    b.HasIndex("Sha256");

                    b.HasIndex("ScanRootId", "FullPath")
                        .IsUnique();

                    b.ToTable("PhotoAssets");
                });

            modelBuilder.Entity("PhotoSortingApp.Domain.Models.ScanRoot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableDuplicateDetection")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastScanUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("RootPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalFilesLastScan")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RootPath")
                        .IsUnique();

                    b.ToTable("ScanRoots");
                });

            modelBuilder.Entity("PhotoSortingApp.Domain.Models.PhotoAsset", b =>
                {
                    b.HasOne("PhotoSortingApp.Domain.Models.ScanRoot", "ScanRoot")
                        .WithMany("Photos")
                        .HasForeignKey("ScanRootId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScanRoot");
                });

            modelBuilder.Entity("PhotoSortingApp.Domain.Models.ScanRoot", b =>
                {
                    b.Navigation("Photos");
                });
#pragma warning restore 612, 618
        }
    }
}
